### ISSUE TITLE
Security solutions data is failing to upload in pre 7.12 versions

### ISSUE THREAD

**Issue by liza-mae** [elastic/elastic-stack-testing#1083]
Security solutions data is failing to upload in pre 7.12 versions, this appeared to be working a few days ago, so something broke recently, I see this PR checked in recently that may have caused it: https://github.com/elastic/elastic-stack-testing/pull/1079 

Since this is blocking upgrades, I may temporarily remove these tests until it is fixed.

**Comment by MadameSheema** [comment]
Thanks for addressing the issue @liza-mae 

The https://github.com/elastic/elastic-stack-testing/pull/1079 PR is not introducing the issue, actually is fixing an issue introduced by: https://github.com/elastic/elastic-stack-testing/pull/1070 In that PR we were renaming the detection rule file but we didn't update the path where we were using it.

<img width="959" alt="Screenshot 2021-11-22 at 11 17 12" src="https://user-images.githubusercontent.com/17427073/142843875-e6e2144e-8a65-4c7f-a795-43e6d5abb2cb.png">

<img width="2370" alt="Screenshot 2021-11-22 at 11 18 56" src="https://user-images.githubusercontent.com/17427073/142844162-73357a11-de8a-482d-94bb-9f071b450555.png">

After investigating the issue I saw that the problem was also introduced with the https://github.com/elastic/elastic-stack-testing/pull/1070 PR. The problem is with the creation of the Threshold Rule, which works on the latest versions but not on 7.11.x for example. 

This is because between releases we have added new mandatory fields that were not required before:

Required fields on the current version: https://www.elastic.co/guide/en/security/current/rules-api-create.html#req-fields-threshold

Required fields on 7.11: https://www.elastic.co/guide/en/security/7.11/rules-api-create.html#req-fields-threshold

What comes to my mind in order to address this issue is the following:
- Have two different files with the 2 versions of the threshold rule. Depending on the version we start, use one or another.

Can you please confirm if that approach is correct or if there is a different way to tackle the problem? Thanks! :)

**Comment by liza-mae** [comment]
| What comes to my mind in order to address this issue is the following:
|    - Have two different files with the 2 versions of the threshold rule. Depending on the version we start, use one or another.
| Can you please confirm if that approach is correct or if there is a different way to tackle the problem? Thanks! :)

@MadameSheema yes that approach is fine.

**Comment by MadameSheema** [comment]
@liza-mae can you please confirm if this is still an issue? Thanks :)

**Comment by liza-mae** [comment]
@MadameSheema this is fixed, upgrades are not blocked anymore.
