### ISSUE TITLE
Virtualbox is not supported on M1

### ISSUE THREAD

**Issue by liza-mae** [elastic/elastic-stack-testing#1157]
As reported by @gurevichdmitry @kfirpeled - Oracle VM VirtualBox is not supported on M1 which is used for the ansible roles, see: https://discussions.apple.com/thread/253292128.  An enhancement is needed to add other providers, either ```docker``` and/or ```cloud```

**Comment by liza-mae** [comment]
@gurevichdmitry @kfirpeled can you specify what you are needing here?  Do you require an on-prem installation of the stack or can you use elastic cloud (ess)?  If you require an on-prem installation then to get around this issue I can add a docker provider or cloud provider to be used with vagrant.  Let me know what your requirements are.

**Comment by gurevichdmitry** [comment]
@liza-mae, we are developing cloud security posture solution - checking configurations (CIS benchmarks) for Vanilla Kubernetes cluster and later it will be extended to GKE, AKS, ECS, OpenShift. The solution contains new plugin and integration on ELK stack side and beat agent on K8s cluster side. For testing our solution we will need to create different test environments.
Each test environment contains ELK stack deployment and K8s cluster. For testing the agent, the ELK stack shall be a standard deployment. It might be as follows:

- [ ] On-prem solution (as dockers deployment) for ELK and k8s kind / minikube cluster for agent deployment.
- [ ] Improved on-prem solution - two Kubernetes clusters. Cluster-1 shall have ELK stack and Cluster-2 shall have agent deployment.
- [ ] Cloud solution for ELK stack and K8s cluster for agent.

Personally, I prefer two Kubernetes clusters deployment, but it is possible to start from dockers deployment and later to extend to cluster deployment. In order to test the agent side we are planning to use different Kuberenetes versions (1.19, 1.20, 1.21, etc.) and also to change internal cluster's configuration (master and worker nodes count).

For testing integration and plugin on Kibana side we will need a customized ELK deployment (before release - installation that contains our product) and for development purpose it seems like on-prem solution will be preferable because I don't know how much is difficult to publish experimental version of our product to be available for installation on cloud.
We will not cover testing of integration and plugin behaviors on ELK deployment on different OSs (Windows, Ubuntu, etc.).

@kfirpeled, @DaveSys911 please check if I forgot something and we have additional requirements.

Summarizing the above, we can start with docker provider to be used with vagrant, and maybe need to open additional PR for adding support for Kubernetes deployment.

**Comment by liza-mae** [comment]
Thanks @gurevichdmitry for clarifying the requirements.  It is best to add support for kubernetes, if eck will work for you, it was at some point part of this repo and working, but became out of date and so I removed it, I can look to see how much effort to put it back and also applying a fix for this issue about M1/on-prem installation.

**Comment by liza-mae** [comment]
@gurevichdmitry @DaveSys911 This should be supported now, feel free to give it a try.  It is very new, so open issues if you find any.  Please note limitation ```auditbeat``` and ```apm-server``` don’t run with the docker provider, I will need to investigate a bit more on that.   Also, if you had previously tried to run this and are reusing the same directory, remove the ```ait_workspace``` directory before trying again, as you may get a conflict with providers.  The ```README.md``` has also been updated.   Anyway, this is really new and it is more for basic testing, so we may still encounter other limitations.  Having ECK is best for testing more complex scenarios, I will file another issue for adding ECK.

**Comment by DaveSys911** [comment]
@liza-mae Thank you Liza, We will test and let you know
