### ISSUE TITLE
ESTF Monitoring parity tests failing

### ISSUE THREAD

**Issue by ycombinator** [elastic/elastic-stack-testing#181]
Looks like the ESTF Monitoring parity tests for `master` are failing like so:

```
17:30:17 TASK [xpack_metricbeat : Fail if metricbeat process is not running] ************
17:30:17 fatal: [aithost]: FAILED! => {"changed": false, "failed": true, "msg": "metricbeat is not running"}
17:30:17 	to retry, use: --limit @/var/lib/jenkins/workspace/elastic+estf-monitoring-snapshots+master/playbooks/monitoring/docs_parity.retry
17:30:17 
```

(Source: https://internal-ci.elastic.co/view/Stack%20Tests/job/elastic+estf-monitoring-snapshots+master/103/console)

I was able to reproduce this failure locally and do some investigation by looking at logs and configurations for Metricbeat, Kibana, and Elasticsearch on the VM. Here's what I found:

1. Metricbeat fails to start up successfully because it's receiving a 503 response from Kibana. So I looked at Kibana logs...

2. Kibana returns a 503 response because it's not ready. It's not ready because it makes an HTTP (instead of HTTPS) response to Elasticsearch, which fails.

3. Looking at the Kibana configuration file created by Ansible on the VM, it contains this snippet, which I believe is causing the problematic HTTP request from Kibana -> Elasticsearch:

   ```
   elasticsearch.hosts: http://10.0.2.15:9200
   ```

---

I'm not sure what part of the ESTF Ansible configuration is generating this snippet, but I suspect the Monitoring Kibana playbook (https://github.com/elastic/elastic-stack-testing/blob/master/playbooks/monitoring/kibana/docs_parity.yml) is perhaps directly or indirectly using the incorrect `ait_role`s to configure Kibana? 

FWIW, as you can see from the commit history of https://github.com/elastic/elastic-stack-testing/blob/master/playbooks/monitoring/kibana/docs_parity.yml, that file hasn't changed since August 20, 2018. Maybe something in the ESFT Ansible configuration files has changed recently that is causing this failure now?

@liza-mae, would you mind taking a look? Thanks!

**Comment by liza-mae** [comment]
@ycombinator thanks for narrowing it down!  Indeed this is because of a change I made to the kibana roles.  The change I made was a bug fix though :) 

You will need to make the following updates: 

Change `kibana` to `xpack_kibana` here:
https://github.com/elastic/elastic-stack-testing/blob/5ae00a173592bc8e3b79adfac5f12a3b3a361e2b/playbooks/monitoring/kibana/docs_parity.yml#L67

Change `kibana_config` to `xpack_kibana_config` here: 
https://github.com/elastic/elastic-stack-testing/blob/5ae00a173592bc8e3b79adfac5f12a3b3a361e2b/playbooks/monitoring/kibana/docs_parity.yml#L70
 
Give it a try and let me know. 

Also I noticed subsequent failures for builds 104 - 106 were because elasticsearch and kibana were left running from another CI job on that worker machine - so I killed that process to clean up the worker, since my jobs were also failing due to that.  

Thanks !
