### ISSUE TITLE
Output raw JSON files for any mismatching documents 

### ISSUE THREAD

**Issue by igoristic** [elastic/elastic-stack-testing#218]
It would be very helpful to see **raw** JSON dumps if there is ever a comparison mismatch.

Right now the error output in the Jenkins CI is encoded/escaped which makes it a bit difficult to plug into tools like jsondiff.com and do your own investigation.

The only way to get the raw JSON documents right now is to run the tests locally, which might be a bit of an inconvenience for quick/simple test failure investigation

**Comment by ycombinator** [comment]
Hey @igoristic, I recently merged a PR to pretty print the output of the parity tests: https://github.com/elastic/elastic-stack-testing/pull/238.

When it comes to this issue, I think we should **not** pretty print the raw JSON files. Otherwise it would be a lot of scrolling to try and copy the JSON to the clipboard. WDYT?

**Comment by ycombinator** [comment]
This was implemented in https://github.com/elastic/elastic-stack-testing/pull/378.
